/* Generated By:JavaCC: Do not edit this line. jsonsintaxConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface jsonsintaxConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ASIGNACION = 1;
  /** RegularExpression Id. */
  int LBRACE = 2;
  /** RegularExpression Id. */
  int RBRACE = 3;
  /** RegularExpression Id. */
  int LBRACKET = 4;
  /** RegularExpression Id. */
  int RBRACKET = 5;
  /** RegularExpression Id. */
  int COMMA = 6;
  /** RegularExpression Id. */
  int DOTDOT = 7;
  /** RegularExpression Id. */
  int IDENTIFIER = 8;
  /** RegularExpression Id. */
  int NUMBER = 9;
  /** RegularExpression Id. */
  int DECIMAL = 10;
  /** RegularExpression Id. */
  int EXPONENCIAL = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"=\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\":\"",
    "<IDENTIFIER>",
    "<NUMBER>",
    "<DECIMAL>",
    "<EXPONENCIAL>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
  };

}
